export const API_URL = "https://nomad-movies.nomadcoders.workers.dev/movies";
export const COUNTRY_NAMES = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AG: "Antigua and Barbuda",
  AL: "Albania",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BE: "Belgium",
  BG: "Bulgaria",
  BH: "Bahrain",
  BM: "Bermuda",
  BO: "Bolivia",
  BR: "Brazil",
  BS: "Bahamas",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  GF: "French Guiana",
  GI: "Gibraltar",
  GR: "Greece",
  GT: "Guatemala",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croatia",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KR: "South Korea",
  KW: "Kuwait",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  MK: "North Macedonia",
  MT: "Malta",
  MX: "Mexico",
  MY: "Malaysia",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PS: "Palestine",
  PT: "Portugal",
  PY: "Paraguay",
  QA: "Qatar",
  RO: "Romania",
  RS: "Serbia",
  SA: "Saudi Arabia",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SM: "San Marino",
  SV: "El Salvador",
  TC: "Turks and Caicos Islands",
  TH: "Thailand",
  TN: "Tunisia",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  US: "United States",
  UY: "Uruguay",
  VE: "Venezuela",
  YE: "Yemen",
  ZA: "South Africa",
};
